apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-07-08T06:04:57Z"
  labels:
    app: n1
  name: n1
  namespace: default
  resourceVersion: "417980"
  uid: f243f6a2-bfe1-421c-b505-f8c69bac6a48
spec:
  clusterIP: 10.233.32.38
  clusterIPs:
  - 10.233.32.38
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30302
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: n1
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
